export const surpriseMePrompts = [
  "Dota 2 Hero Crystal Maiden in a serene glacial cave, enchanting her staff.",
  "Dota 2 Hero Juggernaut wielding his spinning blade amidst a storm of petals.",
  "Dota 2 Hero Pudge feasting on a banquet of delicacies in a hidden lair.",
  "Dota 2 Hero Enchantress charming wild creatures in an enchanted woodland.",
  "Dota 2 Hero Invoker deciphering ancient texts in a secret arcane library.",
  "Dota 2 Hero Earthshaker splitting the earth open with a mighty leap.",
  "Dota 2 Hero Lina igniting a volcano with her fiery spells.",
  "Dota 2 Hero Sven training with his sword under a waterfall.",
  "Dota 2 Hero Drow Ranger aiming her bow from a hidden perch.",
  "Dota 2 Hero Shadow Fiend harnessing dark energies within a cathedral of shadows.",
  "Dota 2 Hero Witch Doctor dancing around a bonfire in a tribal village.",
  "Dota 2 Hero Nature's Prophet communing with the spirits of the forest.",
  "Dota 2 Hero Templar Assassin blending into the shadows within an ancient ruin.",
  "Dota 2 Hero Clockwerk tinkering with mechanical contraptions in a workshop.",
  "Dota 2 Hero Anti-Mage meditating within a tranquil cave.",
  "Dota 2 Hero Shadow Shaman summoning spirits in a circle of standing stones.",
  "Dota 2 Hero Zeus hurling lightning bolts from the heavens.",
  "Dota 2 Hero Vengeful Spirit seeking revenge in a desolate wasteland.",
  "Dota 2 Hero Outworld Devourer gazing into the cosmos from an observatory.",
  "Dota 2 Hero Slardar guarding a treasure chest deep within an underwater cave.",
  "Dota 2 Hero Bane haunting dreams within a haunted mansion.",
  "Dota 2 Hero Skywrath Mage casting spells from an arcane platform in the sky.",
  "Dota 2 Hero Bloodseeker hunting in a dark and eerie forest.",
  "Dota 2 Hero Sniper taking aim from a hidden vantage point in a war-torn city.",
  "Dota 2 Hero Lion channeling dark magic within a sinister underground chamber.",
  "Dota 2 Hero Phantom Assassin striking from the shadows in a moonlit graveyard.",
  "Dota 2 Hero Riki sneaking through a bustling market with mischievous intent.",
  "Dota 2 Hero Windranger firing arrows from the treetops in a dense forest.",
  "Dota 2 Hero Io floating serenely amidst the stars in the night sky.",
  "Dota 2 Hero Elder Titan shaping the earth in a rocky canyon.",
  "Dota 2 Hero Chen surrounded by a menagerie of animals in a sacred grove.",
  "Dota 2 Hero Lich raising the dead within a haunting ice palace.",
  "Dota 2 Hero Slark prowling through a murky swamp with his stolen treasures.",
  "Dota 2 Hero Tinker inventing contraptions in a cluttered steampunk laboratory.",
  "Dota 2 Hero Centaur Warrunner leading a charge across an open grassland.",
  "Dota 2 Hero Troll Warlord rallying his forces on a snow-covered battlefield.",
  "Dota 2 Hero Dazzle performing a healing ritual at a sacred temple.",
  "Dota 2 Hero Ursa roaring triumphantly atop a mountain peak.",
  "Dota 2 Hero Venomancer spreading his toxic influence in a fetid swamp.",
  "Dota 2 Hero Nyx Assassin lurking in the shadows of an ancient ruined city.",
  "Dota 2 Hero Visage summoning his familiars amidst crumbling gravestones.",
  "Dota 2 Hero Razor harnessing electricity in a stormy wasteland.",
  "Dota 2 Hero Crystal Maiden riding a magical ice sleigh through a starry night.",
  "Dota 2 Hero Morphling shifting forms near a shimmering oasis.",
  "Dota 2 Hero Wraith King ruling over a grand and ancient palace.",
  "Dota 2 Hero Ember Spirit blazing through a forest fire with fiery determination.",
  "Dota 2 Hero Pugna wielding his staff in a ruined city, channeling dark energies.",
  "Dota 2 Hero Rubick casting spells from atop a floating arcane platform.",
  "Dota 2 Hero Brewmaster enjoying a feast in a lively tavern.",
  "Dota 2 Hero Ember Spirit traversing a serene bamboo forest.",
  "Dota 2 Hero Luna riding her celestial mount across a starlit sky.",
  "Dota 2 Hero Axe leading a charge into battle on a snow-covered peak.",
  "Dota 2 Hero Mirana summoning her lunar powers within a sacred grove.",
  "Dota 2 Hero Kunkka commanding his ghost ship in a raging sea.",
  "Dota 2 Hero Queen of Pain unleashing her sonic scream in a desolate wasteland.",
  "Dota 2 Hero Death Prophet communing with spirits in an ancient burial ground.",
  "Dota 2 Hero Necrophos raising the undead in a moonlit cemetery.",
  "Dota 2 Hero Tusk carving his mark on a frozen tundra.",
  "Dota 2 Hero Viper basking in the heat of a scorching desert.",
  "Dota 2 Hero Chaos Knight summoning his chaotic horsemen in a realm of void.",
  "Dota 2 Hero Tiny throwing a massive boulder amidst towering cliffs.",
  "Dota 2 Hero Wisp guiding spirits through an otherworldly portal.",
  "Dota 2 Hero Aghanim conducting magical experiments in a mystical laboratory.",
  "Dota 2 Hero Storm Spirit riding lightning bolts across a stormy sky.",
  "Dota 2 Hero Winter Wyvern soaring over an icy landscape.",
  "Dota 2 Hero Legion Commander leading an armored charge in a battlefield.",
  "Dota 2 Hero Techies setting up explosive traps in a treacherous minefield.",
  "Dota 2 Hero Abaddon emerging from a dark abyss with his cursed armor.",
  "Dota 2 Hero Faceless Void warping time within a cosmic vortex.",
  "Dota 2 Hero Naga Siren enchanting sailors with her mesmerizing song.",
  "Dota 2 Hero Dragon Knight facing a fearsome dragon in a fiery cave.",
  "Dota 2 Hero Lycan transforming under a full moon into a fierce wolf.",
  "Dota 2 Hero Meepo leading a pack of clones in a rocky canyon.",
  "Dota 2 Hero Dark Seer manipulating magnetic fields in a futuristic city.",
  "Dota 2 Hero Riki ambushing enemies from the shadows in an urban alleyway.",
  "Dota 2 Hero Oracle gazing into a pool of prophetic visions.",
  "Dota 2 Hero Undying raising an army of zombies in a decaying graveyard.",
  "Dota 2 Hero Grimstroke painting dark runes with his enchanted brush.",
  "Dota 2 Hero Bristleback charging into battle on a war-torn battlefield.",
  "Dota 2 Hero Pangolier swinging his rapier in a lively tavern brawl.",
  "Dota 2 Hero Huskar leaping into combat with his burning spears.",
  "Dota 2 Hero Wraith King leading a spectral army through a haunted forest.",
  "Dota 2 Hero Weaver weaving a tapestry of time in an ethereal realm.",
  "Dota 2 Hero Puck casting playful spells amidst a dreamscape of colors.",
  "Dota 2 Hero Invoker summoning elemental powers within a sacred sanctuary.",
  "Dota 2 Hero Terrorblade emerging from the depths of a hellish abyss.",
  "Dota 2 Hero Gyrocopter piloting his aircraft through a sky of clouds.",
  "Dota 2 Hero Spectre haunting enemies with spectral daggers in a nightmarish realm.",
  "Dota 2 Hero Medusa petrifying foes with her gaze in a ruined temple.",
  "Dota 2 Hero Ogre Magi juggling fireballs with a mischievous grin.",
  "Dota 2 Hero Dazzle performing a dazzling display of lights at a grand festival.",
  "Dota 2 Hero Ancient Apparition freezing enemies in a land of perpetual ice.",
  "Dota 2 Hero Enigma creating a black hole amidst a starry nebula.",
  "Dota 2 Hero Treant Protector guarding an ancient forest with his mighty presence.",
  "Dota 2 Hero Io forming constellations with its celestial tethers.",
  "Dota 2 Hero Tidehunter battling a colossal sea monster in a raging ocean.",
  "Dota 2 Hero Crystal Maiden enchanting her staff in a serene glacial cave.",
  "Dota 2 Hero Juggernaut wielding his spinning blade amidst a storm of petals.",
  "Dota 2 Hero Pudge feasting on a banquet of delicacies in a hidden lair.",
  "Dota 2 Hero Enchantress charming wild creatures in an enchanted woodland.",
  "Dota 2 Hero Invoker deciphering ancient texts in a secret arcane library.",
  "Dota 2 Hero Earthshaker splitting the earth open with a mighty leap.",
  "Dota 2 Hero Lina igniting a volcano with her fiery spells.",
  "Dota 2 Hero Sven training with his sword under a waterfall.",
  "Dota 2 Hero Drow Ranger aiming her bow from a hidden perch.",
  "Dota 2 Hero Shadow Fiend harnessing dark energies within a cathedral of shadows.",
  "Dota 2 Hero Witch Doctor dancing around a bonfire in a tribal village.",
  "Dota 2 Hero Nature's Prophet communing with the spirits of the forest.",
  "Dota 2 Hero Templar Assassin blending into the shadows within an ancient ruin.",
  "Dota 2 Hero Clockwerk tinkering with mechanical contraptions in a workshop.",
  "Dota 2 Hero Anti-Mage meditating within a tranquil cave.",
  "Dota 2 Hero Shadow Shaman summoning spirits in a circle of standing stones.",
  "Dota 2 Hero Zeus hurling lightning bolts from the heavens.",
  "Dota 2 Hero Vengeful Spirit seeking revenge in a desolate wasteland.",
  "Dota 2 Hero Outworld Devourer gazing into the cosmos from an observatory.",
  "Dota 2 Hero Slardar guarding a treasure chest deep within an underwater cave.",
  "Dota 2 Hero Bane haunting dreams within a haunted mansion.",
  "Dota 2 Hero Skywrath Mage casting spells from an arcane platform in the sky.",
  "Dota 2 Hero Bloodseeker hunting in a dark and eerie forest.",
  "Dota 2 Hero Sniper taking aim from a hidden vantage point in a war-torn city.",
  "Dota 2 Hero Lion channeling dark magic within a sinister underground chamber.",
  "Dota 2 Hero Phantom Assassin striking from the shadows in a moonlit graveyard.",
  "Dota 2 Hero Riki sneaking through a bustling market with mischievous intent.",
  "Dota 2 Hero Windranger firing arrows from the treetops in a dense forest.",
  "Dota 2 Hero Io floating serenely amidst the stars in the night sky.",
  "Dota 2 Hero Elder Titan shaping the earth in a rocky canyon.",
  "Dota 2 Hero Chen surrounded by a menagerie of animals in a sacred grove.",
  "Dota 2 Hero Lich raising the dead within a haunting ice palace.",
  "Dota 2 Hero Slark prowling through a murky swamp with his stolen treasures.",
  "Dota 2 Hero Tinker inventing contraptions in a cluttered steampunk laboratory.",
  "Dota 2 Hero Centaur Warrunner leading a charge across an open grassland.",
  "Dota 2 Hero Troll Warlord rallying his forces on a snow-covered battlefield.",
  "Dota 2 Hero Dazzle performing a healing ritual at a sacred temple.",
  "Dota 2 Hero Ursa roaring triumphantly atop a mountain peak.",
  "Dota 2 Hero Venomancer spreading his toxic influence in a fetid swamp.",
  "Dota 2 Hero Nyx Assassin lurking in the shadows of an ancient ruined city.",
  "Dota 2 Hero Visage summoning his familiars amidst crumbling gravestones.",
  "Dota 2 Hero Razor harnessing electricity in a stormy wasteland.",
  "Dota 2 Hero Crystal Maiden riding a magical ice sleigh through a starry night.",
  "Dota 2 Hero Morphling shifting forms near a shimmering oasis.",
  "Dota 2 Hero Wraith King ruling over a grand and ancient palace.",
  "Dota 2 Hero Ember Spirit blazing through a forest fire with fiery determination.",
  "Dota 2 Hero Pugna wielding his staff in a ruined city, channeling dark energies.",
  "Dota 2 Hero Rubick casting spells from atop a floating arcane platform.",
  "Dota 2 Hero Brewmaster enjoying a feast in a lively tavern.",
  "Dota 2 Hero Ember Spirit traversing a serene bamboo forest.",
  "Dota 2 Hero Luna riding her celestial mount across a starlit sky.",
  "Dota 2 Hero Axe leading a charge into battle on a snow-covered peak.",
  "Dota 2 Hero Mirana summoning her lunar powers within a sacred grove.",
  "Dota 2 Hero Kunkka commanding his ghost ship in a raging sea.",
  "Dota 2 Hero Queen of Pain unleashing her sonic scream in a desolate wasteland.",
  "Dota 2 Hero Death Prophet communing with spirits in an ancient burial ground.",
  "Dota 2 Hero Necrophos raising the undead in a moonlit cemetery.",
  "Dota 2 Hero Tusk carving his mark on a frozen tundra.",
  "Dota 2 Hero Viper basking in the heat of a scorching desert.",
  "Dota 2 Hero Chaos Knight summoning his chaotic horsemen in a realm of void.",
  "Dota 2 Hero Tiny throwing a massive boulder amidst towering cliffs.",
  "Dota 2 Hero Wisp guiding spirits through an otherworldly portal.",
  "Dota 2 Hero Aghanim conducting magical experiments in a mystical laboratory.",
  "Dota 2 Hero Storm Spirit riding lightning bolts across a stormy sky.",
  "Dota 2 Hero Winter Wyvern soaring over an icy landscape.",
  "Dota 2 Hero Legion Commander leading an armored charge in a battlefield.",
  "Dota 2 Hero Techies setting up explosive traps in a treacherous minefield.",
  "Dota 2 Hero Abaddon emerging from a dark abyss with his cursed armor.",
  "Dota 2 Hero Faceless Void warping time within a cosmic vortex.",
  "Dota 2 Hero Naga Siren enchanting sailors with her mesmerizing song.",
  "Dota 2 Hero Dragon Knight facing a fearsome dragon in a fiery cave.",
  "Dota 2 Hero Lycan transforming under a full moon into a fierce wolf.",
  "Dota 2 Hero Meepo leading a pack of clones in a rocky canyon.",
  "Dota 2 Hero Dark Seer manipulating magnetic fields in a futuristic city.",
  "Dota 2 Hero Riki ambushing enemies from the shadows in an urban alleyway.",
  "Dota 2 Hero Oracle gazing into a pool of prophetic visions.",
  "Dota 2 Hero Undying raising an army of zombies in a decaying graveyard.",
  "Dota 2 Hero Grimstroke painting dark runes with his enchanted brush.",
  "Dota 2 Hero Bristleback charging into battle on a war-torn battlefield.",
  "Dota 2 Hero Pangolier swinging his rapier in a lively tavern brawl.",
  "Dota 2 Hero Huskar leaping into combat with his burning spears.",
  "Dota 2 Hero Wraith King leading a spectral army through a haunted forest.",
  "Dota 2 Hero Weaver weaving a tapestry of time in an ethereal realm.",
  "Dota 2 Hero Puck casting playful spells amidst a dreamscape of colors.",
  "Dota 2 Hero Invoker summoning elemental powers within a sacred sanctuary.",
  "Dota 2 Hero Terrorblade emerging from the depths of a hellish abyss.",
  "Dota 2 Hero Gyrocopter piloting his aircraft through a sky of clouds.",
  "Dota 2 Hero Spectre haunting enemies with spectral daggers in a nightmarish realm.",
  "Dota 2 Hero Medusa petrifying foes with her gaze in a ruined temple.",
  "Dota 2 Hero Ogre Magi juggling fireballs with a mischievous grin.",
  "Dota 2 Hero Dazzle performing a dazzling display of lights at a grand festival.",
  "Dota 2 Hero Ancient Apparition freezing enemies in a land of perpetual ice.",
  "Dota 2 Hero Enigma creating a black hole amidst a starry nebula.",
  "Dota 2 Hero Treant Protector guarding an ancient forest with his mighty presence.",
  "Dota 2 Hero Io forming constellations with its celestial tethers.",
  "Dota 2 Hero Tidehunter battling a colossal sea monster in a raging ocean.",
  "Dota 2 Hero Crystal Maiden enchanting her staff in a serene glacial cave.",
  "Dota 2 Hero Juggernaut wielding his spinning blade amidst a storm of petals.",
  "Dota 2 Hero Pudge feasting on a banquet of delicacies in a hidden lair.",
  "Dota 2 Hero Enchantress charming wild creatures in an enchanted woodland.",
  "Dota 2 Hero Invoker deciphering ancient texts in a secret arcane library.",
  "Dota 2 Hero Earthshaker splitting the earth open with a mighty leap.",
  "Dota 2 Hero Lina igniting a volcano with her fiery spells.",
  "Dota 2 Hero Sven training with his sword under a waterfall.",
  "Dota 2 Hero Drow Ranger aiming her bow from a hidden perch.",
  "Dota 2 Hero Shadow Fiend harnessing dark energies within a cathedral of shadows.",
  "Dota 2 Hero Witch Doctor dancing around a bonfire in a tribal village.",
  "Dota 2 Hero Nature's Prophet communing with the spirits of the forest.",
  "Dota 2 Hero Templar Assassin blending into the shadows within an ancient ruin.",
  "Dota 2 Hero Clockwerk tinkering with mechanical contraptions in a workshop.",
  "Dota 2 Hero Anti-Mage meditating within a tranquil cave.",
  "Dota 2 Hero Shadow Shaman summoning spirits in a circle of standing stones.",
  "Dota 2 Hero Zeus hurling lightning bolts from the heavens.",
  "Dota 2 Hero Vengeful Spirit seeking revenge in a desolate wasteland.",
  "Dota 2 Hero Outworld Devourer gazing into the cosmos from an observatory.",
  "Dota 2 Hero Slardar guarding a treasure chest deep within an underwater cave.",
  "Dota 2 Hero Bane haunting dreams within a haunted mansion.",
  "Dota 2 Hero Skywrath Mage casting spells from an arcane platform in the sky.",
  "Dota 2 Hero Bloodseeker hunting in a dark and eerie forest.",
  "Dota 2 Hero Sniper taking aim from a hidden vantage point in a war-torn city.",
  "Dota 2 Hero Lion channeling dark magic within a sinister underground chamber.",
  "Dota 2 Hero Phantom Assassin striking from the shadows in a moonlit graveyard.",
  "Dota 2 Hero Riki sneaking through a bustling market with mischievous intent.",
  "Dota 2 Hero Windranger firing arrows from the treetops in a dense forest.",
  "Dota 2 Hero Io floating serenely amidst the stars in the night sky.",
  "Dota 2 Hero Elder Titan shaping the earth in a rocky canyon.",
  "Dota 2 Hero Chen surrounded by a menagerie of animals in a sacred grove.",
  "Dota 2 Hero Lich raising the dead within a haunting ice palace.",
  "Dota 2 Hero Slark prowling through a murky swamp with his stolen treasures.",
  "Dota 2 Hero Tinker inventing contraptions in a cluttered steampunk laboratory.",
  "Dota 2 Hero Centaur Warrunner leading a charge across an open grassland.",
  "Dota 2 Hero Troll Warlord rallying his forces on a snow-covered battlefield.",
  "Dota 2 Hero Dazzle performing a healing ritual at a sacred temple.",
  "Dota 2 Hero Ursa roaring triumphantly atop a mountain peak.",
  "Dota 2 Hero Venomancer spreading his toxic influence in a fetid swamp.",
  "Dota 2 Hero Nyx Assassin lurking in the shadows of an ancient ruined city.",
  "Dota 2 Hero Visage summoning his familiars amidst crumbling gravestones.",
  "Dota 2 Hero Razor harnessing electricity in a stormy wasteland.",
  "Dota 2 Hero Crystal Maiden riding a magical ice sleigh through a starry night.",
  "Dota 2 Hero Morphling shifting forms near a shimmering oasis.",
  "Dota 2 Hero Wraith King ruling over a grand and ancient palace.",
  "Dota 2 Hero Ember Spirit blazing through a forest fire with fiery determination.",
  "Dota 2 Hero Pugna wielding his staff in a ruined city, channeling dark energies.",
];
